import { buildCommunityIndex } from "./build-community-index.mjs";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { loadContent, readJson, validateOverrides } from "./journey-content.mjs";

export const escapeHtml = value => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
const script = (name, data) => `/* Generated by scripts/build-site.mjs. Edit content sources instead. */\nwindow.${name} = ${JSON.stringify(data).replaceAll("<", "\\u003c")};\n`;
const brandFiles = ["icon.svg", "favicon-16.png", "favicon-32.png", "apple-touch-icon.png", "share.png"];
const assetHash = value => crypto.createHash("sha256").update(value).digest("hex").slice(0, 12);
function siteHead(root, { title, description, page = "", preview = false } = {}) {
  const site = readJson(path.join(root, "content/site.json"));
  const asset = name => `./assets/brand/${name}?v=${assetHash(fs.readFileSync(path.join(root, "content/branding", name)))}`;
  const image = new URL(asset("share.png"), site.url).href;
  const imageAlt = "A white globe inside an orange-tipped map pin on a blue square.";
  const meta = (name, value, type = "property") => `<meta ${type}="${name}" content="${escapeHtml(value)}" />`;
  return [
    `<link rel="icon" type="image/png" sizes="16x16" href="${asset("favicon-16.png")}" />`,
    `<link rel="icon" type="image/png" sizes="32x32" href="${asset("favicon-32.png")}" />`,
    `<link rel="icon" type="image/svg+xml" sizes="any" href="${asset("icon.svg")}" />`,
    `<link rel="apple-touch-icon" sizes="180x180" href="${asset("apple-touch-icon.png")}" />`,
    meta("og:site_name", site.name), meta("og:type", "website"),
    meta("og:title", title || site.name), meta("og:description", description || site.description),
    ...(!preview ? [meta("og:url", new URL(page, site.url).href)] : []),
    meta("og:image", image), meta("og:image:type", "image/png"),
    meta("og:image:width", "1200"), meta("og:image:height", "630"), meta("og:image:alt", imageAlt),
    meta("twitter:card", "summary_large_image", "name"),
    meta("twitter:title", title || site.name, "name"), meta("twitter:description", description || site.description, "name"),
    meta("twitter:image", image, "name"), meta("twitter:image:alt", imageAlt, "name")
  ].join("\n    ");
}
function renderCatalogPage(root, page = "") {
  return fs.readFileSync(path.join(root, "content/templates/catalog.html"), "utf8").replace("{{siteHead}}", siteHead(root, { page }));
}
export function readOverrides(root) {
  const drafts = readJson(path.join(root, "build/studio-draft-overrides.json"), {});
  return Object.fromEntries([["photos", "photo"], ["routes", "route"], ["days", "day"]].map(([key, file]) => [key, { ...(drafts[key] || {}), ...readJson(path.join(root, `content/${file}-overrides.json`), {}) }]));
}
export function renderJourneyPage(root, journey, { preview = false } = {}) {
  let html = fs.readFileSync(path.join(root, "content/templates/journey.html"), "utf8");
  const fields = { ...journey, badge: journey.badge || (journey.kind === "demo" ? "FICTIONAL SAMPLE" : "JOURNEY"), description: journey.subtitle || journey.title };
  html = html.replace(/\{\{(\w+)\}\}/g, (_, key) => key === "siteHead"
    ? siteHead(root, { title: `${journey.title} · Journey Atlas`, description: fields.description, page: journey.kind === "demo" ? "demo.html" : journey.slug, preview })
    : escapeHtml(fields[key]));
  if (journey.kind === "demo") html = html.replace(`<body data-journey-id=`, `<body data-journey-scope="demo" data-journey-id=`);
  if (preview) html = html.replaceAll('./assets/', '/dist/assets/').replace(/src="\/dist\/assets\/(journeys|route-geometry|trip-photos|content-overrides)\.js[^\"]*"/g, (_, asset) => `src="/api/preview-assets/${asset}.js"`).replaceAll('href="./"', 'href="/dist/"').replaceAll('href="./demo.html"', 'href="/dist/demo.html"');
  return html;
}
export function studioAsset(root, name) {
  const { data, routes } = loadContent(root, { includeDrafts: true });
  const outputs = { journeys: ["JOURNEY_ATLAS_DATA", data], "route-geometry": ["JOURNEY_ATLAS_ROUTE_GEOMETRY", routes], "trip-photos": ["JOURNEY_ATLAS_PHOTOS", Object.fromEntries(data.journeys.map(j => [j.id, j.photos]))], "content-overrides": ["JOURNEY_ATLAS_CONTENT_OVERRIDES", readOverrides(root)] };
  if (!outputs[name]) throw new Error("Unknown asset");
  return script(...outputs[name]);
}
export function buildSite(root) {
  const { data, routes } = loadContent(root, { includeDrafts: true });
  const overrides = readOverrides(root);
  validateOverrides(overrides, data);
  const published = data.journeys.filter(j => j.published);
  if (!published.some(j => j.id === data.defaultJourneyId)) throw new Error("Default journey must be published");
  const routeIds = new Set(published.flatMap(j => j.segments.map(s => s.id)));
  const dayIds = new Set(published.flatMap(j => j.days.map(d => d.id)));
  const visiblePhotos = new Map(published.map(j => [j.id, j.photos.filter(photo => !overrides.photos[photo.id]?.trashed && photo.assetStatus !== "local")]));
  const photoIds = new Set([...visiblePhotos.values()].flat().map(p => p.id));
  const select = (obj, ids) => Object.fromEntries(Object.entries(obj).filter(([id]) => ids.has(id)).sort(([a], [b]) => a.localeCompare(b)));
  const publicData = { ...data, journeys: published.map(({ photoImport, timeZone, ...j }) => ({ ...j, ...(j.pointsOfInterest ? {pointsOfInterest:j.pointsOfInterest.map(point=>({...point,...(point.photoIds ? {photoIds:point.photoIds.filter(id=>photoIds.has(id))} : {})}))} : {}), photos: [], ...(j.videos ? { videos: j.videos.filter(video => !video.hidden && video.assetStatus !== "local").map(({sourceHash,...video})=>{if(video.visibility==='private'){const {transcript,captions,captionLanguage,...safe}=video;return safe;}return video;}) } : {}) })) };
  const photoService = readJson(path.join(root, "content/photo-service.json"), { origin: "" });
  if (photoService.origin && (new URL(photoService.origin).origin !== photoService.origin || !photoService.origin.startsWith("https://"))) throw new Error("Photo service must use an HTTPS origin");
  const outputs = new Map([
    ["assets/photo-service.js", script("JOURNEY_ATLAS_PHOTO_SERVICE", photoService)],
    ["assets/journeys.js", script("JOURNEY_ATLAS_DATA", publicData)],
    ["assets/route-geometry.js", script("JOURNEY_ATLAS_ROUTE_GEOMETRY", select(routes, routeIds))],
    ["assets/trip-photos.js", script("JOURNEY_ATLAS_PHOTOS", Object.fromEntries(published.map(j => [j.id, visiblePhotos.get(j.id)])))],
    ["assets/content-overrides.js", script("JOURNEY_ATLAS_CONTENT_OVERRIDES", { photos: select(overrides.photos, photoIds), routes: select(overrides.routes, routeIds), days: select(overrides.days, dayIds) })]
  ]);
  for (const name of brandFiles) outputs.set(`assets/brand/${name}`, fs.readFileSync(path.join(root, "content/branding", name)));
  const versions = new Map();
  for (const [file, value] of outputs) versions.set(file, assetHash(value));
  for (const file of ["assets/arrival-chapter.js", "assets/arrival-chapter.css", "assets/photo-places.js", "assets/photo-bubbles.js", "assets/photo-bubbles.css", "assets/photo-comments.js", "assets/photo-comments.css", "assets/community-client.js", "assets/places-panel.js", "assets/places-comments.js", "assets/places-comments.css", "assets/map-feedback.js", "assets/map-feedback.css", "assets/map-style.js", "assets/photo-auth.js", "assets/atlas-utils.js", "assets/group-travel.js", "assets/media-utils.js", "assets/group-travel.css", "assets/app.js", "assets/location-labels.js", "assets/catalog.js", "assets/replay-utils.js", "assets/styles.css", "assets/mobile.css", "assets/mobile-ux.js", "assets/input-mode.js"]) versions.set(file, assetHash(fs.readFileSync(path.join(root, "dist", file))));
  const versioned = html => html.replace(/\.\/assets\/((?:brand\/)?[a-z0-9-]+\.(?:js|css|svg|png))(?:\?v=[^\"]*)?/g, (_, file) => `./assets/${file}?v=${versions.get(`assets/${file}`) || "1"}`);
  for (const j of published.filter(j => j.kind === "real")) outputs.set(j.slug, versioned(renderJourneyPage(root, j)));
  const demo = published.find(j => j.kind === "demo");
  if (demo) outputs.set("demo.html", versioned(renderJourneyPage(root, demo)));
  else outputs.set("demo.html", versioned(renderCatalogPage(root, "demo.html")));
  outputs.set("index.html", versioned(renderCatalogPage(root)));
  // Track only generated detail pages; never remove hand-authored public files.
  const manifestFile = path.join(root, "dist/generated-pages.json");
  const oldPages = readJson(manifestFile, []);
  const pages = published.filter(j => j.kind === "real").map(j => j.slug).sort();
  for (const file of oldPages) if (/^[a-z0-9-]+\.html$/.test(file) && !["index.html", "demo.html", "404.html"].includes(file) && !pages.includes(file)) fs.rmSync(path.join(root, "dist", file), { force: true });
  outputs.set("generated-pages.json", `${JSON.stringify(pages)}\n`);
  for (const [file, value] of outputs) {
    const target = path.join(root, "dist", file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(`${target}.tmp`, value);
    fs.renameSync(`${target}.tmp`, target);
  }
  buildCommunityIndex(root);
  return { journeys: published.length, drafts: data.journeys.length - published.length, pages };
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { console.log(buildSite(path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."))); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
